name: mongocli # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A snap of the mongocli tool.
description: Control your Atlas clusters!
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  mongocli:
    plugin: go
    source: https://github.com/mongodb/mongocli
    source-type: git
apps:
  mongocli:
    command: mongocli